-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgEKnVyHUanOK/AoPH
/gWT9C7nUMxeOqlFvUrDsO2YxGOgCgYIKoZIzj0DAQehRANCAAQ1BS7ukxlWrpgq
OPaqZycGrC+v0vnfK9TOtkfA3tZjHoECpnWBdf+4JVa2R7w+Y9aCP38SOlthQ02Z
ik/2Zt1+
-----END PRIVATE KEY-----